<a href="https://colab.research.google.com/github/reettginotra/LeetCode_Solutions/blob/main/Battery_life.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import os
from glob import glob

# ==========================
# Specify folder paths
# ==========================
folder1 = "/content/recommissioned_batteries"
folder2 = "/content/regular_alt_batteries"
folder3 = "/content/second_life_batteries"

folders = {
    "folder1": folder1,
    "folder2": folder2,
    "folder3": folder3
}

# ==========================
# Merge CSVs in each folder
# ==========================
for folder_name, folder_path in folders.items():

    csv_files = glob(os.path.join(folder_path, "*.csv"))

    print(f"\nProcessing {folder_name}")
    print(f"Found {len(csv_files)} CSV files")

    df_list = []

    for file in csv_files:
        try:
            df = pd.read_csv(file)
            df_list.append(df)
            print(f"Loaded: {os.path.basename(file)}")
        except Exception as e:
            print(f"Error reading {file}: {e}")

    if len(df_list) > 0:
        merged_df = pd.concat(df_list, ignore_index=True)

        output_file = f"/content/merged_{folder_name}.csv"
        merged_df.to_csv(output_file, index=False)

        print(f"Saved: {output_file}")
        print(f"Shape: {merged_df.shape}")
    else:
        print("No valid CSV files found.")

Processing folder1
Found 5 CSV files
Loaded: battery24.csv
Loaded: battery02.csv
Loaded: battery12.csv
Loaded: battery25.csv

/tmp/ipykernel_3409/1833556219.py:32: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file)

Loaded: battery03.csv
Saved: /content/merged_folder1.csv
Shape: (12727724, 10)

Processing folder2
Found 5 CSV files
Loaded: battery00.csv
Loaded: battery10.csv
Loaded: battery01.csv
Loaded: battery20.csv
Loaded: battery11.csv
Saved: /content/merged_folder2.csv
Shape: (12049033, 10)

Processing folder3
Found 3 CSV files
Loaded: battery36.csv
Loaded: battery13.csv
Loaded: battery54.csv
Saved: /content/merged_folder3.csv
Shape: (7119972, 10)

In [ ]:
recommminedd=pd.read_csv("/content/merged_folder1.csv")
regular=pd.read_csv("/content/merged_folder2.csv")
second_life=pd.read_csv("/content/merged_folder3.csv")

/tmp/ipykernel_3409/2076265441.py:1: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  recommminedd=pd.read_csv("/content/merged_folder1.csv")

In [ ]:
recommminedd

,start_time,time,mode,voltage_charger,temperature_battery,voltage_load,current_load,temperature_mosfet,temperature_resistor,mission_type
0,2022-11-04 11:21:00,0.000,0.0,0.000,0.0,NaN,NaN,NaN,NaN,NaN
1,2022-11-04 11:21:00,0.690,0.0,8.415,23.09,NaN,NaN,NaN,NaN,NaN
2,2022-11-04 11:21:00,1.655,0.0,8.415,23.093,NaN,NaN,NaN,NaN,NaN
3,2022-11-04 11:21:00,2.621,0.0,8.415,23.09,NaN,NaN,NaN,NaN,NaN
4,2022-11-04 11:21:00,3.585,0.0,8.415,23.09,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
12727719,2023-03-13 10:23:00,2210051.172,1.0,8.605,32.624,NaN,NaN,NaN,NaN,NaN
12727720,2023-03-13 10:23:00,2210052.140,1.0,8.606,32.628,NaN,NaN,NaN,NaN,NaN
12727721,2023-03-13 10:23:00,2210053.115,1.0,8.607,32.628,NaN,NaN,NaN,NaN,NaN
12727722,2023-03-13 10:23:00,2210054.083,1.0,8.607,32.632,NaN,NaN,NaN,NaN,NaN
12727723,2023-03-13 10:23:00,2210055.058,1.0,8.607,32.641,NaN,NaN,NaN,NaN,NaN

In [ ]:
regular

,start_time,time,mode,voltage_charger,temperature_battery,voltage_load,current_load,temperature_mosfet,temperature_resistor,mission_type
0,2022-07-19 11:10:00,0.000,0.0,0.000,0.000,NaN,NaN,NaN,NaN,NaN
1,2022-07-19 11:10:00,1.894,0.0,8.341,23.059,NaN,NaN,NaN,NaN,NaN
2,2022-07-19 11:10:00,2.814,0.0,8.340,23.059,NaN,NaN,NaN,NaN,NaN
3,2022-07-19 11:10:00,3.734,0.0,8.341,23.063,NaN,NaN,NaN,NaN,NaN
4,2022-07-19 11:10:00,4.654,0.0,8.341,23.063,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
12049028,2022-11-11 00:31:00,4951134.327,0.0,8.080,22.775,NaN,NaN,NaN,NaN,NaN
12049029,2022-11-11 00:31:00,4951135.326,0.0,8.080,22.771,NaN,NaN,NaN,NaN,NaN
12049030,2022-11-11 00:31:00,4951136.324,0.0,8.080,22.771,NaN,NaN,NaN,NaN,NaN
12049031,2022-11-11 00:31:00,4951137.323,0.0,8.080,22.771,NaN,NaN,NaN,NaN,NaN
12049032,2022-11-11 00:31:00,4951138.331,0.0,8.080,22.771,NaN,NaN,NaN,NaN,NaN

In [ ]:
second_life

,start_time,time,mode,voltage_charger,temperature_battery,voltage_load,current_load,temperature_mosfet,temperature_resistor,mission_type
0,2023-03-16 11:05:00,0.000,0.0,0.000,0.000,NaN,NaN,NaN,NaN,NaN
1,2023-03-16 11:05:00,0.592,0.0,8.089,21.511,NaN,NaN,NaN,NaN,NaN
2,2023-03-16 11:05:00,1.540,0.0,8.090,21.511,NaN,NaN,NaN,NaN,NaN
3,2023-03-16 11:05:00,2.492,0.0,8.089,21.511,NaN,NaN,NaN,NaN,NaN
4,2023-03-16 11:05:00,3.435,0.0,8.090,21.511,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
7119967,2023-04-24 11:12:00,2002667.443,0.0,-0.066,22.783,NaN,NaN,NaN,NaN,NaN
7119968,2023-04-24 11:12:00,2002668.478,0.0,-0.066,22.783,NaN,NaN,NaN,NaN,NaN
7119969,2023-04-24 11:12:00,2002669.512,0.0,-0.065,22.783,NaN,NaN,NaN,NaN,NaN
7119970,2023-04-24 11:12:00,2002670.554,0.0,-0.065,22.783,NaN,NaN,NaN,NaN,NaN
7119971,2023-04-24 11:12:00,2002671.594,0.0,-0.065,22.783,NaN,NaN,NaN,NaN,NaN

In [ ]:
import pandas as pd

recommended = pd.read_csv("/content/merged_folder1.csv")
regular = pd.read_csv("/content/merged_folder2.csv")
second_life = pd.read_csv("/content/merged_folder3.csv")

print(recommended.shape)
print(regular.shape)
print(second_life.shape)

/tmp/ipykernel_10358/1061938008.py:3: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  recommended = pd.read_csv("/content/merged_folder1.csv")

(12727724, 10)
(12049033, 10)
(7119972, 10)

In [ ]:
recommended["battery_class"] = 0
regular["battery_class"] = 1
second_life["battery_class"] = 2

battery_map = {
    0:"Recommended",
    1:"Regular",
    2:"Second_Life"
}

In [ ]:
df = pd.concat(
    [recommended, regular, second_life],
    ignore_index=True
)

print(df.shape)

df.head()

(31896729, 11)

,start_time,time,mode,voltage_charger,temperature_battery,voltage_load,current_load,temperature_mosfet,temperature_resistor,mission_type,battery_class
0,2022-11-04 11:21:00,0.000,0.0,0.000,0.0,NaN,NaN,NaN,NaN,NaN,0
1,2022-11-04 11:21:00,0.690,0.0,8.415,23.09,NaN,NaN,NaN,NaN,NaN,0
2,2022-11-04 11:21:00,1.655,0.0,8.415,23.093,NaN,NaN,NaN,NaN,NaN,0
3,2022-11-04 11:21:00,2.621,0.0,8.415,23.09,NaN,NaN,NaN,NaN,NaN,0
4,2022-11-04 11:21:00,3.585,0.0,8.415,23.09,NaN,NaN,NaN,NaN,NaN,0

In [ ]:
df.info()

df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31896729 entries, 0 to 31896728
Data columns (total 11 columns):
 #   Column                Dtype
---  ------                -----
 0   start_time            object
 1   time                  float64
 2   mode                  float64
 3   voltage_charger       float64
 4   temperature_battery   object
 5   voltage_load          float64
 6   current_load          float64
 7   temperature_mosfet    float64
 8   temperature_resistor  float64
 9   mission_type          float64
 10  battery_class         int64
dtypes: float64(8), int64(1), object(2)
memory usage: 2.6+ GB

,start_time,time,mode,voltage_charger,temperature_battery,voltage_load,current_load,temperature_mosfet,temperature_resistor,mission_type,battery_class
count,31896729,3.189673e+07,3.189673e+07,3.189673e+07,3.189673e+07,4.999189e+06,4.999189e+06,4.999189e+06,4.999189e+06,4.999189e+06,3.189673e+07
unique,258,NaN,NaN,NaN,2.336400e+04,NaN,NaN,NaN,NaN,NaN,NaN
top,2022-07-23 12:31:00,NaN,NaN,NaN,2.275200e+01,NaN,NaN,NaN,NaN,NaN,NaN
freq,309667,NaN,NaN,NaN,1.348700e+04,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,1.619130e+06,3.403296e-01,7.479598e+00,NaN,6.611602e+00,8.452005e+00,2.839761e+01,2.541333e+01,8.304079e-01,8.241904e-01
std,NaN,1.204236e+06,7.334619e-01,9.651102e-01,NaN,6.568094e-01,3.920296e+00,2.317877e+00,2.433727e+00,3.752741e-01,7.689861e-01
min,NaN,0.000000e+00,-1.000000e+00,-1.170000e-01,NaN,-2.700000e-02,1.500000e-01,1.822000e+01,1.938000e+01,0.000000e+00,0.000000e+00
25%,NaN,6.478682e+05,0.000000e+00,6.703000e+00,NaN,6.206000e+00,4.926272e+00,2.683000e+01,2.355000e+01,1.000000e+00,0.000000e+00
50%,NaN,1.387646e+06,0.000000e+00,7.780000e+00,NaN,6.620000e+00,9.479636e+00,2.882000e+01,2.509000e+01,1.000000e+00,1.000000e+00
75%,NaN,2.331140e+06,1.000000e+00,8.238000e+00,NaN,7.032000e+00,9.810288e+00,3.006000e+01,2.612000e+01,1.000000e+00,1.000000e+00
max,NaN,4.951798e+06,1.000000e+00,1.217000e+01,NaN,9.058000e+00,1.978194e+01,3.416000e+01,3.609000e+01,1.000000e+00,2.000000e+00

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))

sns.heatmap(
    df.isnull(),
    cbar=False
)

plt.title("Missing Values")
plt.show()

NameError: name 'df' is not defined

In [ ]:
df.drop_duplicates(inplace=True)

df.reset_index(drop=True,inplace=True)

df.isnull().sum()

In [ ]:
df['start_time'] = pd.to_datetime(
    df['start_time'],
    errors='coerce'
)

df['time'] = pd.to_numeric(
    df['time'],
    errors='coerce'
)

In [ ]:
df['hour'] = df['start_time'].dt.hour

df['day'] = df['start_time'].dt.day

df['month'] = df['start_time'].dt.month

df['weekday'] = df['start_time'].dt.weekday

In [ ]:
df['voltage_diff'] = df['voltage_charger'].diff()

df['voltage_rolling_mean'] = (
    df['voltage_charger']
    .rolling(10)
    .mean()
)

df['voltage_rolling_std'] = (
    df['voltage_charger']
    .rolling(10)
    .std()
)

In [ ]:
df['temp_diff'] = (
    df['temperature_battery']
    .diff()
)

df['temp_rolling_mean'] = (
    df['temperature_battery']
    .rolling(10)
    .mean()
)

df['temp_rolling_std'] = (
    df['temperature_battery']
    .rolling(10)
    .std()
)